### ISSUE TITLE
Preparações - Ambiente

### ISSUE THREAD

**Issue by FelpsGonsales** [FelpsGonsales/RepositorioProjetoEngenharia#1]
Para começar o projeto, vamos organizar o ambiente.

Todas as dependências como : 

plataforma a ser utilizada para front-end tal qual back-end.
plataforma a ser utilizada para o banco de dados.
dados do projeto.
Como utilizar as plataformas passo a passo.
Como rodar o projeto.
Dentre outras informações.
Informações adicionais.

Praticamente essa primeira issue será para responder coisas do read.me com mais detalhamento direto.

**Comment by pedrohenriquemansanofranzin** [comment]
Apache;

**Comment by FelpsGonsales** [comment]
Pra banco de dados vamos usar o mysql workbench mesmo pq é o mais fácil

**Comment by FelpsGonsales** [comment]
Está issue está completa devido ao fato do documento readme ter sido atualizado a quase 100%, e todos os passos do ambiente está descrito.

**Comment by FelpsGonsales** [comment]
Está issue está completa, pois todos os tutoriais para se configurar o ambiente está descrita no readme do projeto.
